file_1 = open('file_1.txt', 'w')
question = input('Enter question: ')
choice_a = input('Enter choice "a": ')
choice_b = input('Enter choice "b": ')
choice_c = input('Enter choice "c": ')
choice_d = input('Enter choice "d": ')
answer = input('Enter the correct answer: ')

file_1.write(question)
file_1.write(choice_a)
file_1.write(choice_b)
file_1.write(choice_c)
file_1.write(choice_d)
file_1.write(answer)